[dev]
  command = "vite dev"
  targetPort = 5173
  framework = "svelte-kit"

[build]
  command = "vite build"
  publish = "build"

#[functions]
#  directory = "netlify/functions/"

[[headers]]
  for = "/*"
  [headers.values]
    Header set Permissions-Policy "browsing-topics=()"    
    add_header Permissions-Policy "browsing-topics=()" always;