backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)
local_backend: true
media_folder: "assets/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

i18n:
  structure: multiple_files
  locales: [en, hu, de, es, pt, fr, it, ru, zh, jp, ar, he]

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    delete: false
    folder: "cms/pages"
    path: '{{folder}}/{{slug}}'
    create: true # Allow users to create new documents in this collection
    i18n: true
    slug: "{{id}}"
    identifier_field: id
    summary: "{{folder}}/{{id}}"
    view_groups:
      - label: Folder
        field: folder
    sortable_fields: ['folder']
    fields:
      - { name: "id", label: "Unique ID", widget: "string", i18n: duplicate }
      - { name: "folder", label: "Folder", widget: "string", i18n: true, required: false }
      - { name: "slug", label: "URL alias", widget: "string", i18n: true, required: false }
      - label: "Fallback language"
        name: "fallback"
        i18n: true
        required: false
        widget: "relation"
        file: langs
        collection: "config"
        search_fields: ["langs.*.title"]
        value_field: "langs.*.id"
        display_fields: ["langs.*.title"]
      - { name: "published", label: "Published", widget: "boolean", i18n: true, required: false, default: true }
      - { name: "title", label: "Title (<h1>)", widget: "string", i18n: true, required: false }
      - { label: Meta keywords, name: keywords, widget: string, required: false, i18n: true }
      - { label: Meta description, name: description, widget: string, required: false, i18n: true }
      - { label: Menutitle (short), name: menutitle, widget: string, required: false, i18n: true }
      - label: Blocks
        label_singular: Block
        name: blocks
        widget: list
        i18n: true
        summary: '{{title}}'
        types:
          - label: "Custom block"
            name: "custom"
            summary: 'Custom block: {{block}}'
            fields:
              - label: "Block"
                name: "block"
                widget: "relation"
                collection: "blocks"
                search_fields: ["id", "title"]
                value_field: "id"
                display_fields: ["{{id}} - {{title}}"]
          - label: "Image Gallery"
            name: "images"
            summary: "Image Gallery: {{title}}"
            fields:
              - { label: Header, name: title, widget: string, default: 'Image Gallery', required: false }
              - label: Images
                name: images
                widget: list
                fields:
                  - { label: Image, name: image, widget: image }
                  - { label: Caption, name: caption, widget: string, required: false }
          - label: 'Article'
            name: 'article'
            summary: "Article: {{title}}"
            fields:
              - { label: Header, name: title, widget: string, required: false }
              - { label: Text, name: text, widget: markdown, required: false }
          - label: 'Product link'
            name: 'product'
            summary: "Product: {{title}}"
            fields:
              - { label: Product name, name: title, widget: string, required: false }
              - { label: Text, name: text, widget: markdown, required: false }
              - { label: Image, name: src, widget: image, required: false }
              - label: "Link to"
                name: "link"
                required: false
                widget: "relation"
                collection: "pages"
                search_fields: ["id", "title"]
                value_field: "id"
                display_fields: ["{{folder}}/{{id}}"]
          - label: "Q&As"
            name: "qas"
            summary: "Q&A: {{title}}"
            fields:
              - { label: Header, name: title, widget: string, default: 'Questions & Answers', required: false }
              - label: Items
                name: items
                widget: list
                fields:
                  - { label: Anchor, name: anchor, widget: string }
                  - { label: Question, name: q, widget: string }
                  - { label: Answer, name: text, widget: markdown }

  - name: "blocks"
    label: "Custom blocks"
    label_singular: "Block"
    folder: "cms/blocks"
    create: true
    i18n: true
    slug: "{{id}}"
    identifier_field: id
    fields:
      - { name: "id", label: "Uniqe ID", widget: "string", i18n: duplicate }
      - { name: "title", label: "Title (<h1>)", widget: "string", i18n: true, required: false }
      - { name: "body", label: "Content", widget: "markdown", i18n: true }
      - label: "Fallback language"
        name: "fallback"
        i18n: true
        required: false
        widget: "relation"
        file: langs
        collection: "config"
        search_fields: ["langs.*.title"]
        value_field: "langs.*.id"
        display_fields: ["langs.*.title"]

  - name: config
    label: Settings
    files:
      - label: "Languages"
        name: "langs"
        file: "cms/config/langs.yml"
        fields:
          - label: Languages
            label_singular: Lang
            name: langs
            delete: false
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Label, name: title, widget: string }
              - { label: Flag, name: flag, widget: image, required: false }
              - label: Text direction
                name: dir
                default: "ltr"
                widget: select
                options:
                  - { label: "Left to right", value: "ltr" }
                  - { label: "Right to left", value: "rtl" }
              - label: Font Face
                name: font
                default: "default"
                widget: select
                options:
                  - { label: "Default", value: "default" }
                  - { label: "Serif", value: "serif" }

  - name: danger
    label: Danger zone
    files:
      - label: "Danger zone"
        name: "danger"
        file: "assets/admin/config.yml"
        fields:
          - label: Languages
            label_singular: Lang
            name: i18n
            delete: false
            fields:
              - { name: locales, label: Lacales, widget: string }

#- name: hidden
#  label: Hidden
#  create: false
#  i18n:
#    structure: single_file
#  files:
#    - label: "Languages"
#      name: "langss"
#      file: "cms/config/langss.yml"
#      i18n: true
#      identifier_field: id
#      fields:
#        - { label: ID, name: id, i18n: true, widget: string }
#        - { label: Label, name: title, i18n: true, widget: string }
#        - { label: Flag, name: flag, i18n: true, widget: image, required: false }
#        - label: Text direction
#          name: dir
#          i18n: true
#          default: "ltr"
#          widget: select
#          options:
#            - { label: "Left to right", value: "ltr" }
#            - { label: "Right to left", value: "rtl" }
#        - label: Font Face
#          name: font
#          i18n: true
#          default: "default"
#          widget: select
#          options:
#            - { label: "Default", value: "default" }
#            - { label: "Serif", value: "serif" }
