- label: Image Gallery
  name: images
  summary: "Image Gallery: {{title}}"
  fields:
    - label: Header
      name: title
      widget: string
      default: Image Gallery
      required: false
    - label: Images
      name: images
      widget: list
      fields:
        - label: Image
          name: image
          widget: image
        - label: Caption
          name: caption
          widget: string
          required: false
- label: Article
  name: article
  summary: "Article: {{title}}"
  fields:
    - label: Header
      name: title
      widget: string
      required: false
    - label: subhead
      name: subhead
      widget: text
      required: false
    - label: Text
      name: text
      widget: markdown
      required: false
- label: Product link
  name: product
  summary: "Product: {{title}}"
  fields:
    - label: Product name
      name: title
      widget: string
      required: false
    - label: Text
      name: text
      widget: markdown
      required: false
    - label: Image
      name: src
      widget: image
      required: false
    - label: Link to
      name: link
      required: false
      widget: relation
      collection: pages
      search_fields:
        - id
        - title
      value_field: id
      display_fields:
        - "{{folder}}/{{id}}"
- label: Q&As
  name: qas
  summary: "Q&A: {{title}}"
  fields:
    - label: Header
      name: title
      widget: string
      default: Questions & Answers
      required: false
    - label: subhead
      name: subhead
      widget: text
      required: false
    - label: Items
      name: items
      identifier_field: anchor
      summary: "{{anchor}} - {{q}}"
      widget: list
      fields:
        - label: Anchor
          name: anchor
          widget: string
        - label: Question
          name: q
          widget: string
        - label: Answer
          name: text
          widget: markdown
