langs:
  - id: en
    title: English
    dir: ltr
    font: default
  - dir: ltr
    font: default
    id: hu
    title: Matyar
  - dir: ltr
    font: default
    id: de
    title: Deu
  - id: ru
    title: Russian
    dir: ltr
    font: default
  - id: pt
    title: Portugal
    dir: ltr
    font: default
  - id: jp
    title: Japanese
    dir: ltr
    font: default
  - id: it
    title: Italian
    dir: ltr
    font: default
  - id: fr
    title: Français
    dir: ltr
    font: default
  - id: es
    title: Español
    dir: ltr
    font: default
  - id: zh
    title: Chinese
    dir: ltr
    font: default
  - id: ar
    title: Arabic
    dir: rtl
    font: default
  - id: he
    title: Hebrew
    dir: rtl
    font: default
