de:
  id: de
  title: Deutsch
  dir: ltr
  font: default
  active: false
ru:
  id: ru
  title: Russian
  dir: ltr
  font: default
  active: true
ko:
  id: ko
  title: Korean
  dir: ltr
  font: default
pt:
  id: pt
  title: Portugal
  dir: ltr
  font: default
jp:
  id: jp
  title: Japanese
  dir: ltr
  font: default
en:
  id: en
  title: English
  dir: ltr
  font: default
  active: true
it:
  id: it
  title: Italian
  dir: ltr
  font: default
fr:
  id: fr
  title: Français
  dir: ltr
  font: default
hu:
  id: hu
  title: Magyar
  dir: ltr
  font: default
  active: true
es:
  id: es
  title: Español
  dir: ltr
  font: default
zh:
  id: zh
  title: Chinese
  dir: ltr
  font: default
ar:
  id: ar
  title: Arabic
  dir: rtl
  font: default
he:
  id: he
  title: Hebrew
  dir: rtl
  font: default
tr:
  id: tr
  title: Turkish
  dir: ltr
  font: default
